image: gcc

HClient-Release:
  stage: build
  variables:
    GIT_DEPTH: "1"
  before_script:
    - |
        apt update && apt -y install libsdl1.2-dev zlib1g-dev libfreetype6-dev libnotify-dev libopus-dev tar gcc
        if [ ! -x ~/bam-0.5.0/bam ]; then
          wget -O ~/bamv0.5.0.tar.gz https://github.com/matricks/bam/archive/v0.5.0.tar.gz
          tar -zxvf ~/bamv0.5.0.tar.gz -C ~/
          cd ~/bam-0.5.0; ./make_unix.sh
          cd $CI_PROJECT_DIR
        fi
  script: 
    - ~/bam-0.5.0/bam release
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - data/
      - teeworlds
      - teeworlds_srv
      - license.txt
      - storage.cfg
  cache:
    paths:
        - ~/bam-0.5.0/

HClient-Debug:
  stage: build
  variables:
    GIT_DEPTH: "1"
  before_script:
    - |
        apt update && apt -y install libsdl1.2-dev zlib1g-dev libfreetype6-dev libnotify-dev libopus-dev tar gcc
        if [ ! -x ~/bam-0.5.0/bam ]; then
          wget -O ~/bamv0.5.0.tar.gz https://github.com/matricks/bam/archive/v0.5.0.tar.gz
          tar -zxvf ~/bamv0.5.0.tar.gz -C ~/
          cd ~/bam-0.5.0; ./make_unix.sh
          cd $CI_PROJECT_DIR
        fi
  script: 
    - ~/bam-0.5.0/bam debug
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - data/
      - teeworlds_d
      - teeworlds_srv_d
      - license.txt
      - storage.cfg
  cache:
    paths:
        - ~/bam-0.5.0/