image: Visual Studio 2015

install:
  - cmd: |
      call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
      call "C:\Program Files (x86)\Microsoft Visual Studio 15.0\VC\vcvarsall.bat" x86_amd64
      cd C:\projects
      curl -LfsS -o bam.zip https://github.com/matricks/bam/archive/v0.5.0.zip
      7z x bam.zip
      cd bam-0.5.0\ & make_win64_msvc.bat
      cd C:\projects\hclient

build_script:
  - cmd: ..\bam-0.5.0\bam.exe client_release
  - cmd: ..\bam-0.5.0\bam.exe server_release

artifacts:
  - path: teeworlds*
    name: H-Client
