image: Visual Studio 2015

environment:
  HCLIENT_VERSION: 4.0.1

init:
  - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86
  
install:
  - IF NOT EXIST C:\projects\bam-0.5.0 (
    cd C:\projects &&
    curl -LfsS -o bam.zip https://github.com/matricks/bam/archive/v0.5.0.zip &&
    7z x bam.zip &&
    cd bam-0.5.0\ && 
    make_win64_msvc.bat &&
    cd C:\projects\hclient)
      
cache:
  - C:\projects\bam-0.5.0

build_script:
  - cmd: ..\bam-0.5.0\bam.exe release
  - cmd: ..\bam-0.5.0\bam.exe debug
  
after_build:
  - "SET PATH=C:\\Python27-x64;C:\\Python27-x64\\Scripts;%PATH%"
  - python scripts\make_release.py %HCLIENT_VERSION% win32
 
artifacts:
  - path: H-Client-*.zip
          teeworlds*.exe
          teeworlds*.pdb
    name: H-Client Win32
