image: Visual Studio 2015

install:
  - cmd: |
      cd C:\projects
      curl -LfsS -o bam.zip https://github.com/matricks/bam/archive/v0.5.0.zip
      7z x bam.zip
      cd bam-0.5.0\ & make_win64_msvc.bat
      cd C:\projects\hclient

build_script:
  - cmd: |
      InitVCEnv.bat
      ..\bam-0.5.0\bam.exe client_release
  - cmd: |
      InitVCEnv.bat
      ..\bam-0.5.0\bam.exe server_release

artifacts:
  - path: teeworlds*
    name: H-Client
