name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-cmake:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, windows-2022]
        include:
        - name: "Ubuntu-Latest x86_64"
          os: ubuntu-latest
          cmake-args: -G "Unix Makefiles"
          build-args: --parallel
          package-file: Teelink-linux_x86_64.tar.gz
          env:
            CFLAGS: -Wdeclaration-after-statement -Wduplicated-branches
            CXXFLAGS: -Wduplicated-branches
            
        - name: "Windows x64"
          os: windows-latest
          cmake-args: -G "Visual Studio 17 2022" -A x64
          package-file: Teelink-win64.zip
          env:
            CFLAGS: /WX
            CXXFLAGS: /WX
            LDFLAGS: /WX

        - name: "Windows x86"
          os: windows-2022
          cmake-args: -G "Visual Studio 17 2022" -A Win32
          package-file: Teelink-win32.zip
          env:
            CFLAGS: /WX
            CXXFLAGS: /WX
            LDFLAGS: /WX

    steps:
    - name: Checkout submodules
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Prepare Linux
      if: contains(matrix.os, 'ubuntu')
      run: |
        sudo apt-get update -y
        sudo apt-get install pkg-config cmake libfreetype6-dev libsdl-dev libicu-dev libssl-dev libcurl4-openssl-dev -y
        sudo apt install bam git libfreetype6-dev libsdl2-dev libpnglite-dev libwavpack-dev python3 libnotify-dev libgdk-pixbuf2.0-0 libopus-dev -y
    - name: Build
      env: ${{ matrix.env }}
      run: |
        mkdir release
        bam release
        mv data release
        mv teelink release
        mv license.txt release
        mv storage.cfg release
        tar -cfz ${{ matrix.package-file }} release
    - name: Package(Linux)
      if: contains(matrix.os, 'ubuntu')
      run: |
        cd release
        mkdir artifacts
        mv ${{ matrix.package-file }} ..
        cd ..
        mv ${{ matrix.package-file }} release/artifacts
    - name: Package(Windows)
      if: contains(matrix.os, 'windows')
      run: |
        mkdir release/artifacts
        cd release
        mv ${{ matrix.package-file }} ..
        cd ..
        7z a ${{ matrix.package-full-file }} ${{ matrix.package-file }}
        mv ${{ matrix.package-full-file }} release/artifacts
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2-preview
      with:
        name: ${{ matrix.name }}
        path: release/artifacts/${{ matrix.package-full-file }}